### ISSUE TITLE
Цвета gruvbox по умолчанию

### ISSUE THREAD

**Issue by Linuxoid85** [CalmiraLinux/ascetico#1]
https://gist.github.com/kamek-pf/2eae4f570061a97788a8a9ca4c893797

```yml
# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
```
